### ISSUE TITLE
[Bug] Cannot run example on iOS with swift version 4.2.1

### ISSUE THREAD

**Issue by VictorUvarov** [rurico/flutter_video_compress#39]
### Description
My Swift version:
```
Apple Swift version 4.2.1 (swiftlang-1000.11.42 clang-1000.11.45.1)
Target: x86_64-apple-darwin18.6.0
```

Unable to run the example. The error says: 
``` 
Launching lib/main.dart on iPhone XR in debug mode...
Xcode build done.                                            1.7s
Failed to build iOS app
Error output from Xcode build:
↳
    ** BUILD FAILED **
Xcode's output:
↳
    === BUILD TARGET video_player OF PROJECT Pods WITH CONFIGURATION Debug ===
    The “Swift Language Version” (SWIFT_VERSION) build setting must be set to a supported value for targets which use Swift. Supported values are: 3.0, 4.0, 4.2. This setting can be set in the build settings editor.
Could not build the application for the simulator.
Error launching application on iPhone XR.
Exited (sigterm)
``` 

### Platform
iOS

### Backtracking step
  1. clone this repo https://github.com/rurico/flutter_video_compress.git
  2. cd flutter_video_compress/example/
  3. flutter packages get
  4. flutter run

### Expected solution
Does the plugin support swift 4.2?

**Comment by rurico** [comment]
yeah, I using Swift 5.0.
I performed the same operation and did not encounter this problem.
```bash
git clone https://github.com/rurico/flutter_video_compress.git testPlugin
cd testPlugin
flutter packages get
flutter emulators --launch Apple
flutter run
Launching lib/main.dart on iPhone Xʀ in debug mode...
Running pod install...                                              4.0s
Running Xcode build...                                                  
                                                   
 ├─Assembling Flutter resources...                           3.0s
 └─Compiling, linking and signing...                        21.6s
Xcode build done.                                           49.3s
Syncing files to device iPhone Xʀ...                                    
 2,548ms (!)                                       

🔥  To hot reload changes while running, press "r". To hot restart (and rebuild state),
press "R".
```

Environment version

```
Apple Swift version 5.0.1 (swiftlang-1001.0.82.4 clang-1001.0.46.5)
Target: x86_64-apple-darwin18.5.0
CocoaPods version 1.7.3
Flutter version 1.5.4-hotfix.2 at /Users/ryu/flutter
```

Maybe you need to cd the `example/ios` folder and run `pod update`.

**Comment by VictorUvarov** [comment]
I tried to cd into ```example/ios``` and running ```pod update```. I also tried opening ```Runner.xcworkspace/``` and changing the swift version to ```4.0``` and ```4.2```. The same error occurs. Any other advice?

**Comment by rurico** [comment]
Would you mind post `pod install --verbose`

**Comment by VictorUvarov** [comment]
Preparing

Analyzing dependencies

Inspecting targets to integrate
  Using `ARCHS` setting to build architectures of target `Pods-Runner`: (``)

Finding Podfile changes
  - Flutter
  - Regift
  - flutter_video_compress
  - image_picker
  - video_player

Fetching external sources
-> Fetching podspec for `Flutter` from `.symlinks/flutter/ios`
-> Fetching podspec for `flutter_video_compress` from `.symlinks/plugins/flutter_video_compress/ios`
-> Fetching podspec for `image_picker` from `.symlinks/plugins/image_picker/ios`
-> Fetching podspec for `video_player` from `.symlinks/plugins/video_player/ios`

Resolving dependencies of `Podfile`

Comparing resolved specification to the sandbox manifest
  - Flutter
  - Regift
  - flutter_video_compress
  - image_picker
  - video_player

Downloading dependencies

-> Using Flutter (1.0.0)

-> Using Regift (1.5.0)

-> Using flutter_video_compress (0.3.0)

-> Using image_picker (0.0.1)

-> Using video_player (0.0.1)
  - Running pre install hooks
    - Podfile

Generating Pods project
  - Creating Pods project
  - Installing files into Pods project
    - Adding source files
    - Adding frameworks
    - Adding libraries
    - Adding resources
    - Adding development pod helper files
    - Linking headers
  - Installing Pod Targets
    - Installing target `Flutter` iOS 8.0
    - Installing target `Regift` iOS 8.0
      - Generating module map file at `Pods/Target Support Files/Regift/Regift.modulemap`
      - Generating umbrella header at `Pods/Target Support Files/Regift/Regift-umbrella.h`
      - Generating Info.plist file at `Pods/Target Support Files/Regift/Regift-Info.plist`
      - Generating dummy source at `Pods/Target Support Files/Regift/Regift-dummy.m`
    - Installing target `flutter_video_compress` iOS 8.0
      - Generating module map file at `Pods/Target Support Files/flutter_video_compress/flutter_video_compress.modulemap`
      - Generating umbrella header at `Pods/Target Support Files/flutter_video_compress/flutter_video_compress-umbrella.h`
      - Generating Info.plist file at `Pods/Target Support Files/flutter_video_compress/flutter_video_compress-Info.plist`
      - Generating dummy source at `Pods/Target Support Files/flutter_video_compress/flutter_video_compress-dummy.m`
    - Installing target `image_picker` iOS 8.0
      - Generating module map file at `Pods/Target Support Files/image_picker/image_picker.modulemap`
      - Generating umbrella header at `Pods/Target Support Files/image_picker/image_picker-umbrella.h`
      - Generating Info.plist file at `Pods/Target Support Files/image_picker/image_picker-Info.plist`
      - Generating dummy source at `Pods/Target Support Files/image_picker/image_picker-dummy.m`
    - Installing target `video_player` iOS 8.0
      - Generating module map file at `Pods/Target Support Files/video_player/video_player.modulemap`
      - Generating umbrella header at `Pods/Target Support Files/video_player/video_player-umbrella.h`
      - Generating Info.plist file at `Pods/Target Support Files/video_player/video_player-Info.plist`
      - Generating dummy source at `Pods/Target Support Files/video_player/video_player-dummy.m`
  - Installing Aggregate Targets
    - Installing target `Pods-Runner` iOS 8.0
      - Generating Info.plist file at `Pods/Target Support Files/Pods-Runner/Pods-Runner-Info.plist`
      - Generating module map file at `Pods/Target Support Files/Pods-Runner/Pods-Runner.modulemap`
      - Generating umbrella header at `Pods/Target Support Files/Pods-Runner/Pods-Runner-umbrella.h`
      - Generating dummy source at `Pods/Target Support Files/Pods-Runner/Pods-Runner-dummy.m`
  - Generating deterministic UUIDs
  - Stabilizing target UUIDs
  - Running post install hooks
    - Podfile
  - Writing Xcode project file to `Pods/Pods.xcodeproj`
  Cleaning up sandbox directory
  - Writing Lockfile in `Podfile.lock`
  - Writing Manifest in `Pods/Manifest.lock`

Integrating client project

Integrating target `Pods-Runner` (`Runner.xcodeproj` project)
  - Running post install hooks
    - cocoapods-stats from `/Library/Ruby/Gems/2.3.0/gems/cocoapods-stats-1.1.0/lib/cocoapods_plugin.rb`

-> Pod installation complete! There are 5 dependencies from the Podfile and 5 total pods installed.

[!] CocoaPods did not set the base configuration of your project because your project already has a custom config set. In order for CocoaPods integration to work at all, please either set the base configurations of the target `Runner` to `Target Support Files/Pods-Runner/Pods-Runner.profile.xcconfig` or include the `Target Support Files/Pods-Runner/Pods-Runner.profile.xcconfig` in your build configuration (`Flutter/Release.xcconfig`).

**Comment by VictorUvarov** [comment]
I updated Xcode to use 5.0 on another computer and it builds. But crashes after it starts compressing.

**Comment by rurico** [comment]
I want to know which platform has crashed. Will help me to locate the problem.

**Comment by rurico** [comment]
I really want to help you, but you haven't provided me with enough information.

**Comment by VictorUvarov** [comment]
iOS is the platform that crashed. What additional information do you require?

**Comment by VictorUvarov** [comment]
I fixed the issue by updating Xcode to the newest version.

**Comment by lifenautjoe** [comment]
I'm getting the error 

```
↳
    fatal error: module map file '/Users/lifenautjoe/Documents/code/okuna/okuna-app/build/ios/Debug-iphoneos/Regift/Regift.modulemap' not found
    fatal error: module map file '/Users/lifenautjoe/Documents/code/okuna/okuna-app/build/ios/Debug-iphoneos/Regift/Regift.modulemap' not found
    1 error generated.
    2 errors generated.
```
