### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by iremecem** [rurico/flutter_video_compress#46]
### Description
Regift.swift file gives an error at line 303, "let tolerance = CMTimeMakeWithSeconds(Constants.TimeInterval, Constants.Tolerance)". Xcode wants this line as "let tolerance = CMTimeMakeWithSeconds(Float64(Constants.TimeInterval), preferredTimescale: Int32(Constants.Tolerance))"
When I fix them and run app it works. But the following day it crashes because of this line. Cannot build app without changing this line. I use latest versions of both swift and xcode.

### Platform
IOS

**Comment by GustavoContreiras** [comment]
if show error of Regift
```
pre_install do |installer|
  installer.analysis_result.specifications.each do |s|
      if s.name == 'Regift'
        s.swift_version = '4.0'
    # elsif s.name == 'other-Plugin'
    #   s.swift_version = '5.0'
    # else
    #   s.swift_version = '4.0'
      end
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['ENABLE_BITCODE'] = 'NO'
    end
  end
end
```
