### ISSUE TITLE
[Bug] this happens when I subscribe to compressor

### ISSUE THREAD

**Issue by sepehr13494** [rurico/flutter_video_compress#78]
### Code Example (if has)
```dart
void main() {
final _flutterVideoCompress = FlutterVideoCompress();
            _conpressSubscription = _flutterVideoCompress.compressProgress$.subscribe((progress) {
                  debugPrint('progress: $progress');
                });
            File myFile = _file;
            debugPrint(_file.lengthSync().toString());
            final info = await _flutterVideoCompress.getMediaInfo(_file.path);
            print(info.toJson());
            if (info.duration > 120 || _file.lengthSync() > 5000000) {
              Fluttertoast.showToast(msg: 'در حال کم کردن حجم....');
              VideoQuality quality = VideoQuality.HighestQuality;
              if (_file.lengthSync() > 5000000) {
                quality = VideoQuality.MediumQuality;
              }
              final info2 = await _flutterVideoCompress.compressVideo(
                _file.path,
                startTime: 0,
                duration: 120,
                quality: quality, // default(VideoQuality.DefaultQuality)
                deleteOrigin: false, // default(false)
              );
              debugPrint(info2.toJson().toString());
              myFile = info2.file;
            }
}
```

this is the log :
I/flutter ( 6520): progress: 0.0
I/flutter ( 6520): progress: 0.0
I/flutter ( 6520): progress: 0.0
I/flutter ( 6520): progress: 0.0
I/flutter ( 6520): progress: 0.0
I/flutter ( 6520): progress: 0.0
I/flutter ( 6520): progress: 0.0
I/flutter ( 6520): progress: 0.0
I/flutter ( 6520): progress: 0.0
I/flutter ( 6520): progress: 0.0
I/flutter ( 6520): progress: 0.0
I/flutter ( 6520): progress: 0.0
I/flutter ( 6520): progress: 0.0
I/flutter ( 6520): progress: 0.0
I/flutter ( 6520): progress: 0.0
I/flutter ( 6520): progress: 0.0
I/flutter ( 6520): progress: 0.0
I/flutter ( 6520): progress: 0.0
I/flutter ( 6520): progress: 0.0
I/flutter ( 6520): progress: 0.0
I/flutter ( 6520): progress: 0.0
I/flutter ( 6520): {path: /storage/emulated/0/Android/data/netonote.ir.netonote/files/flutter_video_compress/VID_20191221_010843_056.mp4, title: , author: , width: 2700, ......

**Comment by aarajput** [comment]
I am facing same issue.

**Comment by febg11** [comment]
I ave this aswell but it prints 100

**Comment by vahid75hj** [comment]
i have same issue i

**Comment by hungtran2492** [comment]
I have same issue. How to fix it?

**Comment by Bidhanrai** [comment]
anyone got any fixes for this?

**Comment by ccamba** [comment]
I have same issue.

**Comment by kleytonstn** [comment]
I just opened the pull request #93  that solves that issue

**Comment by roberthook823** [comment]
I have same issue.
